---
abstract: 'Yet Uh-nother wiki'
author:
  - 'Andrew Sterling Hanenkamp <hanenkamp@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yukki
requires:
  CHI: 0
  Digest::SHA1: 0
  File::Copy::Recursive: 0
  File::Path: 0
  File::ShareDir: 0
  Git::Repository: 0
  HTTP::Throwable::Factory: 0
  IO::Prompter: 0
  JSON: 0
  LWP::MediaTypes: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Params::Validate: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Structured: 0
  Number::Bytes::Human: 0
  Path::Class: 0
  Path::Router: 0
  Path::Router::Route: 0
  Path::Router::Route::Match: 0
  Plack::Request: 0
  Plack::Response: 0
  Plack::Session::Store::Cache: 0
  Scalar::Util: 0
  Template::Semantic: 0
  Text::MultiMarkdown: 0
  Throwable::Error: 0
  Try::Tiny: 0
  URI::Escape: 0
  XML::Twig: 0
  YAML: 0
  autodie: 0
  perl: 5.12.1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Yukki
  repository: git://github.com/zostay/Yukki.git
version: 0.110850
